// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTodo struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

type Msg struct {
	Message string `json:"message"`
}

type SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignUpInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type Todo struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	User        *User  `json:"user"`
}

type UpdateTodo struct {
	Description string `json:"description"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
