package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"app/graph/model"
	"context"
	"fmt"
)

// SignIn is the resolver for the signIn field.
func (r *mutationResolver) SignIn(ctx context.Context, signInInput model.SignInInput) (*model.User, error) {
	panic(fmt.Errorf("not implemented: signIn - signIn"))
}

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, signUpInput model.SignUpInput) (*model.User, error) {
	panic(fmt.Errorf("not implemented: SignUp - signUp"))
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (*model.Msg, error) {
	panic(fmt.Errorf("not implemented: Logout - logout"))
}
